services:
  arlocal:
    image: textury/arlocal:v1.1.66
    command: ['node', 'bin/index.js', '--hidelogs']
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:1984']
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - '1984:1984'

  arns-service:
    image: ghcr.io/ar-io/arns-service:latest
    logging:
      driver: none
    ports:
      - '3000:3000'
    environment:
      - LOG_LEVEL=error
      - GATEWAY_HOST=arlocal
      - GATEWAY_PORT=1984
      - GATEWAY_PROTOCOL=http
      - PREFETCH_CONTRACTS=false
      - BOOTSTRAP_CONTRACTS=false
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:3000/healthcheck']
      interval: 10s
      timeout: 5s
      retries: 5
    depends_on:
      - arlocal

  test-runner:
    build:
      context: .
      dockerfile: Dockerfile.test
    environment:
      - REMOTE_CACHE_URL=http://arns-service:3000
      - GATEWAY_HOST=arlocal
      - GATEWAY_PORT=1984
      - GATEWAY_PROTOCOL=http
    volumes:
      - ./coverage:/app/coverage
